apiVersion: v1
data:
  ENV_VAR_1: fake
  ENV_VAR_2: faker
  LOGS_API_AUTH_TOKEN: ""
  redis_wait.sh: |
    until [ `redis-cli -a  --no-auth-warning -h  -p  ping` = 'PONG' ]
    do
      echo waiting for redis;
      sleep 2;
    done
  sometext: sometext
kind: ConfigMap
metadata:
  name: example-config
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJ0dGwuc2giOnsiYXV0aCI6IllXSmpPakV5TXc9PSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: kotsadm-replicated-registry
  namespace: dmitriykots
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: example
    component: nginx
  name: example-nginx
spec:
  ports:
  - port: 80
  selector:
    app: example
    component: nginx
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: example
    component: nginx
  name: example-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
      component: nginx
  template:
    metadata:
      labels:
        app: example
        component: nginx
    spec:
      containers:
      - image: proxy.replicated.com/proxy/dmitriykots/replicated/license-api:85e08ab
        name: from-docker
      - image: ttl.sh/dmitriykots2/chatops:f3c689e
        name: from-quay
      - image: ttl.sh/dmitriykots2/dmitriy-dev-console:latest
        name: from-ecr
      - image: ttl.sh/dmitriykots2/dmitriy:0.1
        name: from-gcr
      - image: ttl.sh/dmitriykots2/admin-api:1.0
        name: admin-api
      - env:
        - name: from_admin_username
          value: admin4
        envFrom:
        - configMapRef:
            name: example-config
        - configMapRef:
            name: travis-api
        image: ttl.sh/dmitriykots2/nginx:latest
        name: nginx
        resources:
          limits:
            cpu: 500m
      imagePullSecrets:
      - name: kotsadm-replicated-registry
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: example-nginx
spec:
  selector:
    matchLabels:
      app: example
  serviceName: example-nginx-ss
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - image: ttl.sh/dmitriykots2/node:carbon-jessie
        name: node
      imagePullSecrets:
      - name: kotsadm-replicated-registry
