apiVersion: v1
data:
  ENV_VAR_1: fake
  ENV_VAR_2: faker
  LOGS_API_AUTH_TOKEN: ""
  MULTI_LINE_VAR: |
    ZGZzZGZzZGY=
  redis_wait.sh: |
    until [ `redis-cli -a  --no-auth-warning -h  -p  ping` = 'PONG' ]
    do
      echo password
      echo waiting for redis;
      sleep 2;
    done
  sometext: sometext
kind: ConfigMap
metadata:
  name: example-config
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJwcm94eS5yZXBsaWNhdGVkLmNvbSI6eyJhdXRoIjoiYVhreVRITTVObHB1V2tkemVFaFFaM0ZrWkRKcVRIbE1kemxhT0dJMVRGYzZhWGt5VEhNNU5scHVXa2R6ZUVoUVozRmtaREpxVEhsTWR6bGFPR0kxVEZjPSJ9LCJyZWdpc3RyeS5yZXBsaWNhdGVkLmNvbSI6eyJhdXRoIjoiYVhreVRITTVObHB1V2tkemVFaFFaM0ZrWkRKcVRIbE1kemxhT0dJMVRGYzZhWGt5VEhNNU5scHVXa2R6ZUVoUVozRmtaREpxVEhsTWR6bGFPR0kxVEZjPSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: kotsadm-replicated-registry
  namespace: test
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: example
    component: nginx
  name: example-nginx
spec:
  ports:
  - port: 80
  selector:
    app: example
    component: nginx
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: example
    component: nginx
  name: example-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
      component: nginx
  template:
    metadata:
      labels:
        app: example
        component: nginx
    spec:
      containers:
      - image: redis:latest
        name: redis
        resources:
          limits:
            cpu: 500m
      initContainers:
      - env:
        - name: from_admin_username
          value: admin
        - name: embedded_postgres_password
          value: JCrg3rJLr6sAgEJ_MWP39jUad3GyoBRP
        - name: MULTI_LINE_VAR_BASE64
          value: |
            ZGZzZGZzZGY=
        - name: MULTI_LINE_VAR
          value: dfsdfsdf
        - name: MULTI_LINE_VAR_BROKEN
          value: dfsdfsdf
        envFrom:
        - configMapRef:
            name: example-config
        image: nginx:latest
        name: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: example-nginx
spec:
  selector:
    matchLabels:
      app: example
  serviceName: example-nginx-ss
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - image: node:carbon-jessie
        name: node
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: example
    component: nginx
  name: example-nginx
spec:
  template:
    metadata:
      labels:
        app: example
      name: example-init
    spec:
      containers:
      - command:
        - pwd
        env:
        - name: SENTRY_REDIS_HOST
          value: sentry-redis-master
        image: alpine:latest
        name: example-init-job
      restartPolicy: Never
